### ISSUE TITLE
Comment Functionality

### ISSUE THREAD

**Issue by Unihedro** [bjb568/DevDoodle#91]
We have several tickets relating to comments. This post is of intent to sculpt the commenting system and allow discussion of the system before it's implemented.

Comments will include:
- [x] #38 Ability to be upvoted by other users (rep limit?)
- [ ] #40 Ability to be flagged by other users. A flag queue or auto-deletion will be needed for this to be effective.
- [x] #75 Notifying other users when an at-mention `@mention` is specified
- [x] #130 Ability to be edited by the poster within grace period.
- [ ] #128 Ability to be deleted by the poster (under several conditions?).
- [ ] #129 Have a "`reply`" button for adding an automatic `@mention` into the cursor location of the "Add comment" box (just for convenience)?
